// push-message/client-reactjs/src/views/MessageView/MessageView.jsx
import * as React from 'react';
import Mvc from 'mvc-es6';
import SocketProxy from '../../socket/SocketProxy';

class MessageItemView extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        const {data} = this.props;
        return (
            <li className="replies">
                {data}
            </li>
        );
    }
}

class MessageView extends React.Component {

    constructor(props) {
        super(props);
        this.messages = ["An usage of ezyfox-server"];

        this.state = {
            messages : this.messages
        };
        let mvc = Mvc.getInstance();
        this.messageController = mvc.getController("message");
    }

    componentDidMount() {
        this.messageController.addDefaultView("add", (message) => {
            let newMessages = ["An usage of ezyfox-server", JSON.stringify(message)].concat(this.messages.slice(1));
            this.messages = newMessages.length > 30 ? newMessages.slice(0, 30) : newMessages;
            this.setState({messages: this.messages});
        });
    }

    componentWillUnmount() {
        this.messageController.removeAllViews();
    }

    render() {
        const {messages} = this.state;
        return (
            <div className="messages-wrapper">
                <div className="messages" id="messageListDiv">
                    <ul id="messageListUl">
                        {
                            messages.map((msg, i) => <MessageItemView key={i} data={msg} />)
                        }
                    </ul>
                </div>
            </div>
        );
    }
}

export default MessageView

// push-message/client-vuejs/src/components/MessageView.vue
<template>
    <div id="messages">
        <h3>Welcome to <a href="https://github.com/youngmonkeys/ezyfox-server" target="_blank">ezyfox-server</a> push message</h3>
        <ul>
            <li v-for="message in messages" :key="message">
                {{message}}
            </li>
        </ul>
    </div>
</template>

<script>
import Vuex from 'vuex'
import Mvc from 'mvc-es6';

const store = new Vuex.Store({
  state: {
    messages: []
  },
  mutations: {
    messages: state => state.messages
  }
})

export default {
    el: '#messages',
    computed: {
        messages() {
            return store.state.messages;
        }
    },
    created() {
        let mvc = Mvc.getInstance();
        this.messageController = mvc.getController("message");
        this.messageController.addDefaultView("add", (message) => {
            let newMessages = [JSON.stringify(message)].concat(store.state.messages);
            store.state.messages = newMessages.length > 30 ? newMessages.slice(0, 30) : newMessages;
        });
    }
}
</script>
